// <auto-generated />
using System;
using MarsRover.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarsRover.Migrations
{
    [DbContext(typeof(MarsRoverContext))]
    [Migration("20230204223824_AddedPlateauSizeParams")]
    partial class AddedPlateauSizeParams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarsRover.Models.Rover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FinalDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("FinalPositionX")
                        .HasColumnType("int");

                    b.Property<int?>("FinalPositionY")
                        .HasColumnType("int");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateauMap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlateauSizeX")
                        .HasColumnType("int");

                    b.Property<int>("PlateauSizeY")
                        .HasColumnType("int");

                    b.Property<string>("StartingDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("StartingPositionX")
                        .HasColumnType("int");

                    b.Property<int>("StartingPositionY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rover");
                });
#pragma warning restore 612, 618
        }
    }
}
